name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  IMAGE_NAME: ghcr.io/plohan/network-project-chat-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ".docker/server.Dockerfile"
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
